In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns  

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("miadul/hypertension-risk-prediction-dataset")

print("Path to dataset files:", path)

d:\programing\AI-ML\DATA\Hypertension dataset\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ConnectionError: HTTPSConnectionPool(host='www.kaggle.com', port=443): Max retries exceeded with url: /api/v1/datasets/view/miadul/hypertension-risk-prediction-dataset (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A28CB1DFD0>: Failed to resolve 'www.kaggle.com' ([Errno 11001] getaddrinfo failed)"))

In [ ]:
data = pd.read_csv('hypertension_dataset.csv')

In [ ]:
data.head()

Age  Salt_Intake  Stress_Score       BP_History  Sleep_Duration   BMI  \
0   69          8.0             9           Normal             6.4  25.8   
1   32         11.7            10           Normal             5.4  23.4   
2   78          9.5             3           Normal             7.1  18.7   
3   38         10.0            10     Hypertension             4.2  22.1   
4   41          9.8             1  Prehypertension             5.8  16.2   

      Medication Family_History Exercise_Level Smoking_Status Has_Hypertension  
0            NaN            Yes            Low     Non-Smoker              Yes  
1            NaN             No            Low     Non-Smoker               No  
2            NaN             No       Moderate     Non-Smoker               No  
3  ACE Inhibitor             No            Low     Non-Smoker              Yes  
4          Other             No       Moderate     Non-Smoker               No

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               1985 non-null   int64  
 1   Salt_Intake       1985 non-null   float64
 2   Stress_Score      1985 non-null   int64  
 3   BP_History        1985 non-null   object 
 4   Sleep_Duration    1985 non-null   float64
 5   BMI               1985 non-null   float64
 6   Medication        1186 non-null   object 
 7   Family_History    1985 non-null   object 
 8   Exercise_Level    1985 non-null   object 
 9   Smoking_Status    1985 non-null   object 
 10  Has_Hypertension  1985 non-null   object 
dtypes: float64(3), int64(2), object(6)
memory usage: 170.7+ KB


In [ ]:
data.describe()

Age  Salt_Intake  Stress_Score  Sleep_Duration          BMI
count  1985.000000  1985.000000   1985.000000     1985.000000  1985.000000
mean     50.341058     8.531688      4.979345        6.452242    26.015315
std      19.442042     1.994907      3.142303        1.542207     4.512857
min      18.000000     2.500000      0.000000        1.500000    11.900000
25%      34.000000     7.200000      2.000000        5.400000    23.000000
50%      50.000000     8.500000      5.000000        6.500000    25.900000
75%      67.000000     9.900000      8.000000        7.500000    29.100000
max      84.000000    16.400000     10.000000       11.400000    41.900000

In [ ]:
data.head()

Age  Salt_Intake  Stress_Score       BP_History  Sleep_Duration   BMI  \
0   69          8.0             9           Normal             6.4  25.8   
1   32         11.7            10           Normal             5.4  23.4   
2   78          9.5             3           Normal             7.1  18.7   
3   38         10.0            10     Hypertension             4.2  22.1   
4   41          9.8             1  Prehypertension             5.8  16.2   

      Medication Family_History Exercise_Level Smoking_Status Has_Hypertension  
0            NaN            Yes            Low     Non-Smoker              Yes  
1            NaN             No            Low     Non-Smoker               No  
2            NaN             No       Moderate     Non-Smoker               No  
3  ACE Inhibitor             No            Low     Non-Smoker              Yes  
4          Other             No       Moderate     Non-Smoker               No

In [ ]:
data.isnull().sum()

Age                   0
Salt_Intake           0
Stress_Score          0
BP_History            0
Sleep_Duration        0
BMI                   0
Medication          799
Family_History        0
Exercise_Level        0
Smoking_Status        0
Has_Hypertension      0
dtype: int64

### working on categorical first 

In [ ]:
## BP_History
data['BP_History'].unique()

array(['Normal', 'Hypertension', 'Prehypertension'], dtype=object)

In [ ]:
# using label encoding to convert the column into numbers 

from sklearn.preprocessing import LabelEncoder 
encod = LabelEncoder() 
data['BP_History'] = encod.fit_transform(data['BP_History'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               1985 non-null   int64  
 1   Salt_Intake       1985 non-null   float64
 2   Stress_Score      1985 non-null   int64  
 3   BP_History        1985 non-null   int64  
 4   Sleep_Duration    1985 non-null   float64
 5   BMI               1985 non-null   float64
 6   Medication        1186 non-null   object 
 7   Family_History    1985 non-null   object 
 8   Exercise_Level    1985 non-null   object 
 9   Smoking_Status    1985 non-null   object 
 10  Has_Hypertension  1985 non-null   object 
dtypes: float64(3), int64(3), object(5)
memory usage: 170.7+ KB


In [ ]:
data['Medication'].unique()

array([nan, 'ACE Inhibitor', 'Other', 'Beta Blocker', 'Diuretic'],
      dtype=object)

In [ ]:
data['Medication'] = encod.fit_transform(data['Medication'])

In [ ]:
data['Medication'].unique()

array([4, 0, 3, 1, 2])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               1985 non-null   int64  
 1   Salt_Intake       1985 non-null   float64
 2   Stress_Score      1985 non-null   int64  
 3   BP_History        1985 non-null   int64  
 4   Sleep_Duration    1985 non-null   float64
 5   BMI               1985 non-null   float64
 6   Medication        1985 non-null   int64  
 7   Family_History    1985 non-null   object 
 8   Exercise_Level    1985 non-null   object 
 9   Smoking_Status    1985 non-null   object 
 10  Has_Hypertension  1985 non-null   object 
dtypes: float64(3), int64(4), object(4)
memory usage: 170.7+ KB


In [ ]:
data.head()

Age  Salt_Intake  Stress_Score  BP_History  Sleep_Duration   BMI  \
0   69          8.0             9           1             6.4  25.8   
1   32         11.7            10           1             5.4  23.4   
2   78          9.5             3           1             7.1  18.7   
3   38         10.0            10           0             4.2  22.1   
4   41          9.8             1           2             5.8  16.2   

   Medication Family_History Exercise_Level Smoking_Status Has_Hypertension  
0           4            Yes            Low     Non-Smoker              Yes  
1           4             No            Low     Non-Smoker               No  
2           4             No       Moderate     Non-Smoker               No  
3           0             No            Low     Non-Smoker              Yes  
4           3             No       Moderate     Non-Smoker               No

In [ ]:
data.Exercise_Level.unique()
data['Exercise_Level'] = data['Exercise_Level'].map({'Low':1, 'Moderate':2, 'High':3})

In [ ]:
data['Exercise_Level'].unique()  # converted 

array([1, 2, 3])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               1985 non-null   int64  
 1   Salt_Intake       1985 non-null   float64
 2   Stress_Score      1985 non-null   int64  
 3   BP_History        1985 non-null   int64  
 4   Sleep_Duration    1985 non-null   float64
 5   BMI               1985 non-null   float64
 6   Medication        1985 non-null   int64  
 7   Family_History    1985 non-null   object 
 8   Exercise_Level    1985 non-null   int64  
 9   Smoking_Status    1985 non-null   object 
 10  Has_Hypertension  1985 non-null   object 
dtypes: float64(3), int64(5), object(3)
memory usage: 170.7+ KB


In [ ]:
data['Family_History'].unique()
data['Family_History'] = data['Family_History'].map({'Yes':1, 'No':0})

In [ ]:
data.head()

Age  Salt_Intake  Stress_Score  BP_History  Sleep_Duration   BMI  \
0   69          8.0             9           1             6.4  25.8   
1   32         11.7            10           1             5.4  23.4   
2   78          9.5             3           1             7.1  18.7   
3   38         10.0            10           0             4.2  22.1   
4   41          9.8             1           2             5.8  16.2   

   Medication  Family_History  Exercise_Level Smoking_Status Has_Hypertension  
0           4               1               1     Non-Smoker              Yes  
1           4               0               1     Non-Smoker               No  
2           4               0               2     Non-Smoker               No  
3           0               0               1     Non-Smoker              Yes  
4           3               0               2     Non-Smoker               No

In [ ]:
data['Has_Hypertension'] = encod.fit_transform(data['Has_Hypertension'])

In [ ]:
data['Smoking_Status']=data['Smoking_Status'].map({'Non-Smoker':0 , 'Smoker':1})

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Age               1985 non-null   int64  
 1   Salt_Intake       1985 non-null   float64
 2   Stress_Score      1985 non-null   int64  
 3   BP_History        1985 non-null   int64  
 4   Sleep_Duration    1985 non-null   float64
 5   BMI               1985 non-null   float64
 6   Medication        1985 non-null   int64  
 7   Family_History    1985 non-null   int64  
 8   Exercise_Level    1985 non-null   int64  
 9   Smoking_Status    1985 non-null   int64  
 10  Has_Hypertension  1985 non-null   int64  
dtypes: float64(3), int64(8)
memory usage: 170.7 KB


In [ ]:
feature = data.drop('Has_Hypertension',axis=1)
target = data['Has_Hypertension']

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
feature = scaler.fit_transform(feature)
joblib.dump(scaler,'scaler.pkl')

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(
    feature,target, test_size=0.33, random_state=42)

In [ ]:
X_train.shape , X_test.shape, y_train.shape,y_test.shape

((1329, 10), (656, 10), (1329,), (656,))

In [ ]:
X_train[:1 , ]

array([[ 0.70272371, -0.81813261, -0.63006138, -0.03321532,  0.48498447,
         0.04093453, -1.5237584 , -0.99247166,  0.35650091, -0.63312468]])

In [ ]:
df = pd.DataFrame(X_train)

In [ ]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV 
model = LogisticRegression()
param = {'C' : [1,2,3,4,5,6,7,8,10,100]}
grid = GridSearchCV(estimator=model,param_grid=param,cv=10)

In [ ]:
grid.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 10, 100]})

In [ ]:

pred = grid.predict(X_test)

In [ ]:
from sklearn.metrics import f1_score 
f1_score(y_test,pred)

0.8365243004418262

In [ ]:
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
model_pred = model.predict(X_test)

In [ ]:
f1_score(y_test,model_pred)

0.8365243004418262

In [ ]:
import joblib 

In [ ]:
joblib.dump(model,'hypertension_model.pkl')

['hypertension_model.pkl']

In [ ]:
classifier = joblib.load('hypertension_model.pkl')

In [ ]:
data.head()

Age  Salt_Intake  Stress_Score  BP_History  Sleep_Duration   BMI  \
0   69          8.0             9           1             6.4  25.8   
1   32         11.7            10           1             5.4  23.4   
2   78          9.5             3           1             7.1  18.7   
3   38         10.0            10           0             4.2  22.1   
4   41          9.8             1           2             5.8  16.2   

   Medication  Family_History  Exercise_Level  Smoking_Status  \
0           4               1               1               0   
1           4               0               1               0   
2           4               0               2               0   
3           0               0               1               0   
4           3               0               2               0   

   Has_Hypertension  
0                 1  
1                 0  
2                 0  
3                 1  
4                 0

In [ ]:
def detect_hypertension(list1) : 
    model = joblib.load('hypertension_model.pkl') 
    result = model.predict(list1)
    if result == 1 : 
        print("You have Hypertension problem ")
        print("You have to take Care")
    else : 
        print("No your have Negative In Hypertension problem")





In [ ]:
def input_data() :   
    print("\t  Hypertension Detection   \t ")
    print("Enter the Details in the About you .....")
    Age = int(input("Enter Your Age : "))
    Salt_Intake = float(input('Enter The Salt Intake : '))
    Stress_Score = int(input('Enter the Stress Score : '))
    print('0 : Hypertension , 1 : Normal , 2 : Prehypertension')
    BP_History = int(input('Enter BP History : '))
    Sleep_Duration = int(input('Enter the Sleep Duration : '))
    BMI = int(input("Enter the Body mass index :"))
    print("Enter the values betweeen 1-4 ")	
    Medication = int(input('Enter the BMI Medication : '))
    print("If family member have Hypertention \n Yes : 1 \n No : 0 ")
    Family_History =  int(input("Enter the your Ans : "))
    print("Exercise Details :-  low : 1 , miderate : 2 , high : 3 ")    
    Exercise_Level =  int(input("Enter the Exercise Level : ")) 
    print('Enter the Smoking status  \n Non-Smoker : 0 \n Smoker :1')
    Smoking_Status =  int(input("Enter the Smoking Status : "))
    data = [[Age,Salt_Intake,Stress_Score,BP_History,Sleep_Duration,BMI,Medication,Family_History,Exercise_Level,Smoking_Status]]


	  Hypertension Detection   	 
Enter the Details in the About you .....


TypeError: input() takes 0 positional arguments but 1 was given